includes("test")
includes("DynamicGraph")
includes("DSU")
includes("Heuristic")
add_includedirs("$(projectdir)/include")
set_languages("cxx20")
add_cxflags("-Weverything")
add_cxxflags("-Wno-c++98-compat")
add_cxxflags("-Wno-c++98-compat-pedantic")

